sequenceDiagram
  participant User
  participant air.cab
  participant attestation.id
  participant Gateway_Node
  participant Service_Node
  User->>air.cab: Purchase Ticket
  air.cab->>User: Send Magic Link
  User->>attestation.id: Click Magic Link
  attestation.id->>User: Prompt User to Sign Reservation
  User->>attestation.id: Sign Reservation
  attestation.id->>Gateway_Node: Pass User-signed Token
  Gateway_Node->>Service_Node: Assign Service Node and Forward User-signed Token
  Service_Node->>air.cab: Notify about Token's Activation in the Network
